"""Compact medicine normalization pipeline."""
import re
from typing import Optional

# Core salt synonyms - most common in Indian pharma
SALT_SYNONYMS = {
    "metformin hcl": "metformin hydrochloride",
    "metformin hydrochloride": "metformin hydrochloride",
    "amoxycillin": "amoxicillin",
    "amoxicillin trihydrate": "amoxicillin",
    "paracetamol": "paracetamol",
    "acetaminophen": "paracetamol",
    "amlodipine besylate": "amlodipine",
    "amlodipine": "amlodipine",
    "atorvastatin calcium": "atorvastatin",
    "atorvastatin": "atorvastatin",
    "rosuvastatin calcium": "rosuvastatin",
    "rosuvastatin": "rosuvastatin",
    "pantoprazole sodium": "pantoprazole",
    "pantoprazole": "pantoprazole",
    "esomeprazole magnesium": "esomeprazole",
    "esomeprazole": "esomeprazole",
    "clopidogrel bisulfate": "clopidogrel",
    "clopidogrel": "clopidogrel",
    "losartan potassium": "losartan",
    "losartan": "losartan",
    "telmisartan": "telmisartan",
    "olmesartan medoxomil": "olmesartan",
    "olmesartan": "olmesartan",
    "metoprolol succinate": "metoprolol",
    "metoprolol tartrate": "metoprolol",
    "metoprolol": "metoprolol",
    "glimepiride": "glimepiride",
    "glibenclamide": "glibenclamide",
    "glyburide": "glibenclamide",
    "sitagliptin phosphate": "sitagliptin",
    "sitagliptin": "sitagliptin",
    "vildagliptin": "vildagliptin",
    "linagliptin": "linagliptin",
    "duloxetine hydrochloride": "duloxetine",
    "duloxetine": "duloxetine",
    "pregabalin": "pregabalin",
    "gabapentin": "gabapentin",
    "tramadol hydrochloride": "tramadol",
    "tramadol": "tramadol",
    "aceclofenac": "aceclofenac",
    "etoricoxib": "etoricoxib",
    "celecoxib": "celecoxib",
    "diclofenac sodium": "diclofenac",
    "diclofenac": "diclofenac",
    "ibuprofen": "ibuprofen",
    "azithromycin dihydrate": "azithromycin",
    "azithromycin": "azithromycin",
    "fexofenadine hydrochloride": "fexofenadine",
    "fexofenadine": "fexofenadine",
    "cetirizine hydrochloride": "cetirizine",
    "cetirizine": "cetirizine",
    "loratadine": "loratadine",
    "levocetirizine dihydrochloride": "levocetirizine",
    "levocetirizine": "levocetirizine",
    "ambroxol hydrochloride": "ambroxol",
    "ambroxol": "ambroxol",
    "levosalbutamol": "levosalbutamol",
    "salbutamol": "salbutamol",
    "albuterol": "salbutamol",
    "hydrochlorothiazide": "hydrochlorothiazide",
    "hctz": "hydrochlorothiazide",
    "furosemide": "furosemide",
    "aspirin": "aspirin",
    "acetylsalicylic acid": "aspirin",
    "ramipril": "ramipril",
    "enalapril maleate": "enalapril",
    "enalapril": "enalapril",
    "lisinopril": "lisinopril",
    "nimesulide": "nimesulide",
    "mefenamic acid": "mefenamic acid",
    "clavulanic acid": "clavulanic acid",
    "trypsin": "trypsin",
    "chymotrypsin": "chymotrypsin",
    "bromelain": "bromelain",
    "rutin": "rutin",
    "domperidone maleate": "domperidone",
    "domperidone": "domperidone",
    "ondansetron hydrochloride": "ondansetron",
    "ondansetron": "ondansetron",
    "metoclopramide hydrochloride": "metoclopramide",
    "metoclopramide": "metoclopramide",
    "ranitidine hydrochloride": "ranitidine",
    "ranitidine": "ranitidine",
    "famotidine": "famotidine",
    "chlorpheniramine maleate": "chlorpheniramine",
    "chlorpheniramine": "chlorpheniramine",
    "promethazine hydrochloride": "promethazine",
    "promethazine": "promethazine",
    "diphenhydramine hydrochloride": "diphenhydramine",
    "diphenhydramine": "diphenhydramine",
    "doxylamine succinate": "doxylamine",
    "doxylamine": "doxylamine",
    "phenylephrine hydrochloride": "phenylephrine",
    "phenylephrine": "phenylephrine",
    "pseudoephedrine hydrochloride": "pseudoephedrine",
    "pseudoephedrine": "pseudoephedrine",
    "xylometazoline hydrochloride": "xylometazoline",
    "xylometazoline": "xylometazoline",
    "oxymetazoline hydrochloride": "oxymetazoline",
    "oxymetazoline": "oxymetazoline",
    "naphazoline hydrochloride": "naphazoline",
    "naphazoline": "naphazoline",
    "theophylline": "theophylline",
    "aminophylline": "aminophylline",
    "doxofylline": "doxofylline",
    "pentoxifylline": "pentoxifylline",
    "dipyridamole": "dipyridamole",
    "cilostazol": "cilostazol",
    "ticlopidine hydrochloride": "ticlopidine",
    "ticlopidine": "ticlopidine",
    "prasugrel": "prasugrel",
    "ticagrelor": "ticagrelor",
    "heparin sodium": "heparin",
    "heparin": "heparin",
    "enoxaparin sodium": "enoxaparin",
    "enoxaparin": "enoxaparin",
    "dalteparin sodium": "dalteparin",
    "dalteparin": "dalteparin",
    "fondaparinux sodium": "fondaparinux",
    "fondaparinux": "fondaparinux",
    "rivaroxaban": "rivaroxaban",
    "apixaban": "apixaban",
    "edoxaban": "edoxaban",
    "dabigatran etexilate": "dabigatran",
    "dabigatran": "dabigatran",
    "warfarin sodium": "warfarin",
    "warfarin": "warfarin",
    "acenocoumarol": "acenocoumarol",
    "phenindione": "phenindione",
    "procainamide hydrochloride": "procainamide",
    "procainamide": "procainamide",
    "quinidine sulfate": "quinidine",
    "quinidine": "quinidine",
    "disopyramide phosphate": "disopyramide",
    "disopyramide": "disopyramide",
    "lidocaine hydrochloride": "lidocaine",
    "lidocaine": "lidocaine",
    "mexiletine hydrochloride": "mexiletine",
    "mexiletine": "mexiletine",
    "propafenone hydrochloride": "propafenone",
    "propafenone": "propafenone",
    "flecainide acetate": "flecainide",
    "flecainide": "flecainide",
    "amiodarone hydrochloride": "amiodarone",
    "amiodarone": "amiodarone",
    "dronedarone hydrochloride": "dronedarone",
    "dronedarone": "dronedarone",
    "sotalol hydrochloride": "sotalol",
    "sotalol": "sotalol",
    "ibutilide fumarate": "ibutilide",
    "ibutilide": "ibutilide",
    "dofetilide": "dofetilide",
    "vernakalant": "vernakalant",
    "adenosine": "adenosine",
    "digoxin": "digoxin",
    "digitoxin": "digitoxin",
    "milrinone lactate": "milrinone",
    "milrinone": "milrinone",
    "levosimendan": "levosimendan",
    "dobutamine": "dobutamine",
    "dopamine hydrochloride": "dopamine",
    "dopamine": "dopamine",
    "epinephrine hydrochloride": "epinephrine",
    "epinephrine": "epinephrine",
    "norepinephrine bitartrate": "norepinephrine",
    "norepinephrine": "norepinephrine",
    "methoxamine": "methoxamine",
    "metaraminol": "metaraminol",
    "mephentermine": "mephentermine",
    "isoproterenol hydrochloride": "isoproterenol",
    "isoproterenol": "isoproterenol",
    "isoprenaline hydrochloride": "isoproterenol",
    "isoprenaline": "isoproterenol",
    "salbutamol sulfate": "salbutamol",
    "terbutaline sulfate": "terbutaline",
    "terbutaline": "terbutaline",
    "fenoterol hydrobromide": "fenoterol",
    "fenoterol": "fenoterol",
    "isoetharine hydrochloride": "isoetharine",
    "isoetharine": "isoetharine",
    "metaproterenol sulfate": "metaproterenol",
    "metaproterenol": "metaproterenol",
    "pirbuterol acetate": "pirbuterol",
    "pirbuterol": "pirbuterol",
    "bitolterol mesylate": "bitolterol",
    "bitolterol": "bitolterol",
    "formoterol fumarate": "formoterol",
    "formoterol": "formoterol",
    "arformoterol tartrate": "arformoterol",
    "arformoterol": "arformoterol",
    "salmeterol xinafoate": "salmeterol",
    "salmeterol": "salmeterol",
    "indacaterol maleate": "indacaterol",
    "indacaterol": "indacaterol",
    "olodaterol hydrochloride": "olodaterol",
    "olodaterol": "olodaterol",
    "vilanterol": "vilanterol",
    "umeclidinium bromide": "umeclidinium",
    "umeclidinium": "umeclidinium",
    "tiotropium bromide": "tiotropium",
    "tiotropium": "tiotropium",
    "glycopyrronium bromide": "glycopyrronium",
    "glycopyrronium": "glycopyrronium",
    "aclidinium bromide": "aclidinium",
    "aclidinium": "aclidinium",
    "revefenacin hydrochloride": "revefenacin",
    "revefenacin": "revefenacin",
    "darotropium bromide": "darotropium",
    "darotropium": "darotropium",
    "reproterol hydrochloride": "reproterol",
    "reproterol": "reproterol",
    "tretoquinol hydrochloride": "tretoquinol",
    "tretoquinol": "tretoquinol",
    "carbuterol hydrochloride": "carbuterol",
    "carbuterol": "carbuterol",
    "prenalterol hydrochloride": "prenalterol",
    "prenalterol": "prenalterol",
    "dopexamine hydrochloride": "dopexamine",
    "dopexamine": "dopexamine",
    "ibopamine hydrochloride": "ibopamine",
    "ibopamine": "ibopamine",
    "denopamine hydrochloride": "denopamine",
    "denopamine": "denopamine",
    "levodopa": "levodopa",
    "carbidopa": "carbidopa",
    "entacapone": "entacapone",
    "tolcapone": "tolcapone",
    "opicapone": "opicapone",
    "selegiline hydrochloride": "selegiline",
    "selegiline": "selegiline",
    "rasagiline mesylate": "rasagiline",
    "rasagiline": "rasagiline",
    "safinamide mesylate": "safinamide",
    "safinamide": "safinamide",
    "rotigotine": "rotigotine",
    "pramipexole dihydrochloride": "pramipexole",
    "pramipexole": "pramipexole",
    "ropinirole hydrochloride": "ropinirole",
    "ropinirole": "ropinirole",
    "apomorphine hydrochloride": "apomorphine",
    "apomorphine": "apomorphine",
    "bromocriptine mesylate": "bromocriptine",
    "bromocriptine": "bromocriptine",
    "pergolide mesylate": "pergolide",
    "pergolide": "pergolide",
    "cabergoline": "cabergoline",
    "lisuride maleate": "lisuride",
    "lisuride": "lisuride",
    "quinagolide hydrochloride": "quinagolide",
    "quinagolide": "quinagolide",
    "tetrabenazine": "tetrabenazine",
    "deutetrabenazine": "deutetrabenazine",
    "valbenazine tosylate": "valbenazine",
    "valbenazine": "valbenazine",
    "benztropine mesylate": "benztropine",
    "benztropine": "benztropine",
    "trihexyphenidyl hydrochloride": "trihexyphenidyl",
    "trihexyphenidyl": "trihexyphenidyl",
    "procyclidine hydrochloride": "procyclidine",
    "procyclidine": "procyclidine",
    "biperiden hydrochloride": "biperiden",
    "biperiden": "biperiden",
    "biperiden lactate": "biperiden",
    "orphenadrine hydrochloride": "orphenadrine",
    "orphenadrine": "orphenadrine",
    "orphenadrine citrate": "orphenadrine",
    "cyclobenzaprine hydrochloride": "cyclobenzaprine",
    "cyclobenzaprine": "cyclobenzaprine",
    "tizanidine hydrochloride": "tizanidine",
    "tizanidine": "tizanidine",
    "baclofen": "baclofen",
    "dantrolene sodium": "dantrolene",
    "dantrolene": "dantrolene",
    "methocarbamol": "methocarbamol",
    "carisoprodol": "carisoprodol",
    "chlorzoxazone": "chlorzoxazone",
    "metaxalone": "metaxalone",
    "milnacipran": "milnacipran",
    "venlafaxine": "venlafaxine",
    "desvenlafaxine": "desvenlafaxine",
    "desvenlafaxine succinate": "desvenlafaxine",
    "levomilnacipran": "levomilnacipran",
    "atomoxetine": "atomoxetine",
    "reboxetine": "reboxetine",
    "bupropion hydrochloride": "bupropion",
    "bupropion": "bupropion",
    "mirtazapine": "mirtazapine",
    "trazodone hydrochloride": "trazodone",
    "trazodone": "trazodone",
    "nefazodone": "nefazodone",
    "vilazodone": "vilazodone",
    "vortioxetine": "vortioxetine",
    "agomelatine": "agomelatine",
    "melatonin": "melatonin",
    "ramelteon": "ramelteon",
    "suvorexant": "suvorexant",
    "lemborexant": "lemborexant",
    "zolpidem tartrate": "zolpidem",
    "zolpidem": "zolpidem",
    "zopiclone": "zopiclone",
    "eszopiclone": "eszopiclone",
    "clonazepam": "clonazepam",
    "lorazepam": "lorazepam",
    "alprazolam": "alprazolam",
    "diazepam": "diazepam",
    "clobazam": "clobazam",
    "midazolam hydrochloride": "midazolam",
    "midazolam": "midazolam",
    "buspirone hydrochloride": "buspirone",
    "buspirone": "buspirone",
    "hydroxyzine hydrochloride": "hydroxyzine",
    "hydroxyzine": "hydroxyzine",
    "hydroxyzine pamoate": "hydroxyzine",
    "brompheniramine maleate": "brompheniramine",
    "brompheniramine": "brompheniramine",
    "dexchlorpheniramine maleate": "dexchlorpheniramine",
    "dexchlorpheniramine": "dexchlorpheniramine",
    "triprolidine hydrochloride": "triprolidine",
    "triprolidine": "triprolidine",
    "pheniramine maleate": "pheniramine",
    "pheniramine": "pheniramine",
    "mepyramine maleate": "mepyramine",
    "mepyramine": "mepyramine",
    "antazoline hydrochloride": "antazoline",
    "antazoline": "antazoline",
    "ephedrine hydrochloride": "ephedrine",
    "ephedrine": "ephedrine",
    "proxyphylline": "proxyphylline",
    "bamifylline": "bamifylline",
    "cangrelor": "cangrelor",
    "eptifibatide": "eptifibatide",
    "tirofiban": "tirofiban",
    "abciximab": "abciximab",
    "nadroparin calcium": "nadroparin",
    "nadroparin": "nadroparin",
    "ciprofloxacin hydrochloride": "ciprofloxacin",
    "ciprofloxacin": "ciprofloxacin",
    "ofloxacin": "ofloxacin",
    "levofloxacin": "levofloxacin",
    "moxifloxacin hydrochloride": "moxifloxacin",
    "moxifloxacin": "moxifloxacin",
    "norfloxacin": "norfloxacin",
    "clarithromycin": "clarithromycin",
    "erythromycin": "erythromycin",
    "doxycycline hyclate": "doxycycline",
    "doxycycline": "doxycycline",
    "minocycline": "minocycline",
    "tetracycline": "tetracycline",
    "metronidazole": "metronidazole",
    "tinidazole": "tinidazole",
    "secnidazole": "secnidazole",
    "fluconazole": "fluconazole",
    "itraconazole": "itraconazole",
    "ketoconazole": "ketoconazole",
    "voriconazole": "voriconazole",
    "amphotericin b": "amphotericin b",
    "nystatin": "nystatin",
    "acyclovir": "acyclovir",
    "aciclovir": "acyclovir",
    "valacyclovir": "valacyclovir",
    "valaciclovir": "valacyclovir",
    "oseltamivir phosphate": "oseltamivir",
    "oseltamivir": "oseltamivir",
    "lamivudine": "lamivudine",
    "tenofovir disoproxil fumarate": "tenofovir",
    "tenofovir": "tenofovir",
    "efavirenz": "efavirenz",
    "nevirapine": "nevirapine",
    "atazanavir": "atazanavir",
    "ritonavir": "ritonavir",
    "lopinavir": "lopinavir",
    "darunavir": "darunavir",
    "sofosbuvir": "sofosbuvir",
    "ledipasvir": "ledipasvir",
    "velpatasvir": "velpatasvir",
    "daclatasvir": "daclatasvir",
    "ribavirin": "ribavirin",
    "interferon": "interferon",
    "peginterferon": "peginterferon",
    "methotrexate": "methotrexate",
    "azathioprine": "azathioprine",
    "cyclosporine": "cyclosporine",
    "tacrolimus": "tacrolimus",
    "mycophenolate mofetil": "mycophenolate",
    "mycophenolate": "mycophenolate",
    "hydroxychloroquine sulfate": "hydroxychloroquine",
    "hydroxychloroquine": "hydroxychloroquine",
    "chloroquine phosphate": "chloroquine",
    "chloroquine": "chloroquine",
    "sulfasalazine": "sulfasalazine",
    "mesalazine": "mesalazine",
    "olsalazine": "olsalazine",
    "budesonide": "budesonide",
    "fluticasone propionate": "fluticasone",
    "fluticasone": "fluticasone",
    "montelukast": "montelukast",
    "zafirlukast": "zafirlukast",
    "ketotifen": "ketotifen",
    "bilastine": "bilastine",
    "desloratadine": "desloratadine",
    "rupatadine": "rupatadine",
    "olopatadine": "olopatadine",
    "cyproheptadine hydrochloride": "cyproheptadine",
    "cyproheptadine": "cyproheptadine",
    "meclizine hydrochloride": "meclizine",
    "meclizine": "meclizine",
    "dimenhydrinate": "dimenhydrinate",
    "betahistine dihydrochloride": "betahistine",
    "betahistine": "betahistine",
    "cinnarizine": "cinnarizine",
    "flunarizine dihydrochloride": "flunarizine",
    "flunarizine": "flunarizine",
    "prochlorperazine maleate": "prochlorperazine",
    "prochlorperazine": "prochlorperazine",
    "thiethylperazine": "thiethylperazine",
    "buclizine": "buclizine",
    "cyclizine hydrochloride": "cyclizine",
    "cyclizine": "cyclizine",
    "chlorpromazine hydrochloride": "chlorpromazine",
    "chlorpromazine": "chlorpromazine",
    "haloperidol": "haloperidol",
    "risperidone": "risperidone",
    "olanzapine": "olanzapine",
    "quetiapine fumarate": "quetiapine",
    "quetiapine": "quetiapine",
    "aripiprazole": "aripiprazole",
    "ziprasidone": "ziprasidone",
    "paliperidone": "paliperidone",
    "lurasidone hydrochloride": "lurasidone",
    "lurasidone": "lurasidone",
    "asenapine": "asenapine",
    "clozapine": "clozapine",
    "carbamazepine": "carbamazepine",
    "oxcarbazepine": "oxcarbazepine",
    "phenytoin sodium": "phenytoin",
    "phenytoin": "phenytoin",
    "valproic acid": "valproic acid",
    "sodium valproate": "valproic acid",
    "divalproex sodium": "valproic acid",
    "lamotrigine": "lamotrigine",
    "levetiracetam": "levetiracetam",
    "topiramate": "topiramate",
    "zonisamide": "zonisamide",
    "lacosamide": "lacosamide",
    "vigabatrin": "vigabatrin",
    "tiagabine": "tiagabine",
    "gabapentin enacarbil": "gabapentin",
    "prednisolone": "prednisolone",
    "prednisone": "prednisone",
    "dexamethasone sodium phosphate": "dexamethasone",
    "dexamethasone": "dexamethasone",
    "hydrocortisone": "hydrocortisone",
    "cefuroxime axetil": "cefuroxime",
    "cefuroxime": "cefuroxime",
    "cefixime": "cefixime",
    "cefpodoxime": "cefpodoxime",
    "ceftriaxone": "ceftriaxone",
    "ceftazidime": "ceftazidime",
    "cefotaxime": "cefotaxime",
    "cefalexin": "cefalexin",
    "cephalexin": "cefalexin",
    "sulbactam": "sulbactam",
    "tazobactam": "tazobactam",
    "cilastatin": "cilastatin",
    "imipenem": "imipenem",
    "meropenem": "meropenem",
    "trypsin-chymotrypsin": "trypsin-chymotrypsin",
}

# Dosage form normalization
DOSAGE_FORMS = {
    "tab": "tablet", "tabs": "tablet", "tablet": "tablet", "tablets": "tablet",
    "cap": "capsule", "caps": "capsule", "capsule": "capsule", "capsules": "capsule",
    "syp": "syrup", "syrup": "syrup", "syrups": "syrup",
    "inj": "injection", "injection": "injection", "injections": "injection",
    "drops": "drops", "drop": "drops", "ear drops": "drops", "eye drops": "drops",
    "cream": "cream", "creams": "cream", "ointment": "ointment", "ointments": "ointment",
    "gel": "gel", "gels": "gel", "lotion": "lotion", "lotions": "lotion",
    "powder": "powder", "powders": "powder", "granules": "granules",
    "inhaler": "inhaler", "inhalers": "inhaler", "nebulizer": "nebulizer",
    "patch": "patch", "patches": "patch", "suppository": "suppository", "suppositories": "suppository",
    "suspension": "suspension", "susp": "suspension", "suspensions": "suspension",
    "emulsion": "emulsion", "emulsions": "emulsion",
    "solution": "solution", "solutions": "solution",
    "syringe": "syringe", "syringes": "syringe",
    "vial": "vial", "vials": "vial",
    "ampoule": "ampoule", "ampoules": "ampoule", "amp": "ampoule", "amps": "ampoule",
    "sachet": "sachet", "sachets": "sachet",
    "spray": "spray", "sprays": "spray",
    "lozenge": "lozenge", "lozenges": "lozenge",
    "mouthwash": "mouthwash", "gargle": "gargle",
    "shampoo": "shampoo", "shampoos": "shampoo",
    "soap": "soap", "soaps": "soap",
    "lotion": "lotion", "lotions": "lotion",
    "liniment": "liniment", "liniments": "liniment",
    "paste": "paste", "pastes": "paste",
    "jelly": "jelly", "jellies": "jelly",
    "ointment": "ointment", "ointments": "ointment",
    "cream": "cream", "creams": "cream",
    "gel": "gel", "gels": "gel",
    "lotion": "lotion", "lotions": "lotion",
    "powder": "powder", "powders": "powder",
    "granules": "granules",
    "inhaler": "inhaler", "inhalers": "inhaler",
    "nebulizer": "nebulizer",
    "patch": "patch", "patches": "patch",
    "suppository": "suppository", "suppositories": "suppository",
    "suspension": "suspension", "susp": "suspension", "suspensions": "suspension",
    "emulsion": "emulsion", "emulsions": "emulsion",
    "solution": "solution", "solutions": "solution",
    "syringe": "syringe", "syringes": "syringe",
    "vial": "vial", "vials": "vial",
    "ampoule": "ampoule", "ampoules": "ampoule", "amp": "ampoule", "amps": "ampoule",
    "sachet": "sachet", "sachets": "sachet",
    "spray": "spray", "sprays": "spray",
    "lozenge": "lozenge", "lozenges": "lozenge",
    "mouthwash": "mouthwash", "gargle": "gargle",
    "shampoo": "shampoo", "shampoos": "shampoo",
    "soap": "soap", "soaps": "soap",
    "liniment": "liniment", "liniments": "liniment",
    "paste": "paste", "pastes": "paste",
    "jelly": "jelly", "jellies": "jelly",
}

# Release type patterns
RELEASE_PATTERNS = {
    "extended release": "extended release",
    "extended-release": "extended release",
    "xr": "extended release",
    "er": "extended release",
    "sr": "sustained release",
    "sustained release": "sustained release",
    "sustained-release": "sustained release",
    "cr": "controlled release",
    "controlled release": "controlled release",
    "controlled-release": "controlled release",
    "dr": "delayed release",
    "delayed release": "delayed release",
    "delayed-release": "delayed release",
    "ir": "immediate release",
    "immediate release": "immediate release",
    "immediate-release": "immediate release",
    "la": "long acting",
    "long acting": "long acting",
    "long-acting": "long acting",
    "dispersible": "dispersible",
    "dispersible tablet": "dispersible",
    "enteric coated": "enteric coated",
    "enteric-coated": "enteric coated",
    "gastro-resistant": "enteric coated",
    "gastro resistant": "enteric coated",
    "chewable": "chewable",
    "chewable tablet": "chewable",
    "sublingual": "sublingual",
    "buccal": "buccal",
    "orodispersible": "orodispersible",
    "mouth dissolving": "orodispersible",
    "fast dissolving": "orodispersible",
}


def normalize_salt_name(name: str) -> str:
    """Normalize a salt/ingredient name to its canonical form."""
    if not name:
        return ""
    name = name.strip().lower()
    # Remove common suffixes
    name = re.sub(r'\s+(ip|usp|bp|ep|inj|tab|cap|syp|cream|ointment|gel|drops|syrup|suspension|injection|spray|lotions?|powder|granules|inhaler|nebulizer|patch|suppositories?|emulsion|solution|syringe|vial|ampoules?|sachet|lozenge|mouthwash|gargle|shampoo|soap|liniment|paste|jelly)$', '', name)
    # Remove dosage form words
    name = re.sub(r'\s+(tablets?|capsules?|syrups?|injections?|drops|creams?|ointments?|gels?|lotions?|powders?|granules|inhalers?|nebulizers?|patches|suppositories?|suspensions?|emulsions?|solutions?|syringes|vials?|ampoules?|sachets?|sprays?|lozenges?|mouthwashes?|gargles?|shampoos?|soaps?|liniments?|pastes?|jellies?)$', '', name)
    # Remove strength patterns
    name = re.sub(r'\s*\d+(\.\d+)?\s*(mg|mcg|g|ml|iu|%|units?|w/w|w/v).*$', '', name)
    # Remove "and" combinations
    name = re.sub(r'\s+and\s+.*$', '', name)
    # Remove parentheses content
    name = re.sub(r'\s*\([^)]*\)', '', name)
    # Remove extra spaces
    name = re.sub(r'\s+', ' ', name).strip()
    # Apply synonym mapping
    return SALT_SYNONYMS.get(name, name)


def normalize_dosage_form(form: str) -> str:
    """Normalize dosage form."""
    if not form:
        return ""
    form = form.strip().lower()
    return DOSAGE_FORMS.get(form, form)


def extract_strength(text: str) -> Optional[tuple[float, str]]:
    """Extract strength value and unit from text."""
    if not text:
        return None
    # Match patterns like "500mg", "500 mg", "10mg/5ml", "10 mg/5 ml"
    match = re.search(r'(\d+(?:\.\d+)?)\s*(mg|mcg|g|ml|iu|%|units?|w/w|w/v)\s*(?:/\s*(\d+(?:\.\d+)?)\s*(mg|mcg|g|ml|iu|%|units?|w/w|w/v))?', text, re.IGNORECASE)
    if match:
        value = float(match.group(1))
        unit = match.group(2).lower()
        return (value, unit)
    return None


def extract_release_type(text: str) -> Optional[str]:
    """Extract release type from text."""
    if not text:
        return None
    text_lower = text.lower()
    for pattern, release_type in RELEASE_PATTERNS.items():
        if pattern in text_lower:
            return release_type
    return None


def parse_composition(composition: str) -> list[dict]:
    """Parse a composition string into list of ingredients with strengths."""
    if not composition:
        return []
    ingredients = []
    # Split by comma or "and"
    parts = re.split(r',|\s+and\s+', composition)
    for part in parts:
        part = part.strip()
        if not part:
            continue
        # Extract strength
        strength_info = extract_strength(part)
        # Extract name (remove strength and other noise)
        name = re.sub(r'\s*\d+(\.\d+)?\s*(mg|mcg|g|ml|iu|%|units?|w/w|w/v).*$', '', part, flags=re.IGNORECASE)
        name = re.sub(r'\s*\([^)]*\)', '', name)
        name = re.sub(r'\s+', ' ', name).strip()
        if name:
            ingredients.append({
                "name": name,
                "normalized_name": normalize_salt_name(name),
                "strength": strength_info[0] if strength_info else None,
                "unit": strength_info[1] if strength_info else None,
            })
    return ingredients


def normalize_medicine_name(name: str) -> str:
    """Normalize a medicine/brand name."""
    if not name:
        return ""
    name = name.strip().lower()
    # Remove dosage form
    name = re.sub(r'\s+(tablets?|capsules?|syrups?|injections?|drops|creams?|ointments?|gels?|lotions?|powders?|granules|inhalers?|nebulizers?|patches|suppositories?|suspensions?|emulsions?|solutions?|syringes|vials?|ampoules?|sachets?|sprays?|lozenges?|mouthwashes?|gargles?|shampoos?|soaps?|liniments?|pastes?|jellies?)$', '', name)
    # Remove strength
    name = re.sub(r'\s*\d+(\.\d+)?\s*(mg|mcg|g|ml|iu|%|units?|w/w|w/v).*$', '', name)
    # Remove release type
    for pattern in RELEASE_PATTERNS:
        name = re.sub(r'\s+' + re.escape(pattern) + r'$', '', name)
    # Remove extra spaces
    name = re.sub(r'\s+', ' ', name).strip()
    return name
